[project]
name = "time-table-generator"
version = "0.1.0"
description = "A simple time table generator"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "numpy>=2.3.3",
  "polars>=1.33.1",
]

[dependency-groups]
dev = ["pyright>=1.1.405", "ruff>=0.12.12"]
